from __future__ import annotations
from typing import Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from ..models import Video

class Provider(Protocol):
    def search(self, query: str, limit: int = 20, order: str | None = None, duration: str | None = None, period: str | None = None) -> list[Video]: ...
    def browse_url(self, url: str) -> list[Video]: ...
    def playlist(self, url: str) -> list[Video]: ...
    def channel_tab(self, url: str, tab: str = "videos") -> list[Video]: ...
    def related(self, url: str) -> list[Video]: ...
    def comments(self, url: str, max_comments: int = 100) -> list[Video]: ...
    def channel_url_of(self, video_url: str) -> str | None: ...
    def fetch_formats(self, url: str) -> list[tuple[str, str]]: ...
    def trending(self) -> list[Video]: ...
    def suggestions(self, query: str) -> list[str]: ...