name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WT_CI: "1"  # tell deep_verify to skip GI-dependent checks
      PYTHONUTF8: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint
        run: |
          ruff check .
      - name: Type-check
        run: |
          mypy src/whirltube
      - name: Tests
        run: |
          pytest -q
      - name: Build vendored zipapp
        run: |
          bash scripts/build_zipapp.sh
      - name: Deep verify (CI mode)
        run: |
          bash scripts/deep_verify.sh
