name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout @v4
      - name: Set up Python
        uses: actions/setup-python @v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install project (with dev extras)
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Ruff
        run: |
          ruff --version
          ruff check .
      - name: Mypy
        run: |
          mypy --version
          mypy
      - name: Pytest
        run: |
          pytest -q